// src/languages.ts

export type LanguageCode = string;

export type LanguageMeta = {
  code: LanguageCode;
  nameEn: string;
  nameTh: string;
};

export const LANGUAGES: LanguageMeta[] = [
  { code: 'acn', nameEn: 'Ngochang', nameTh: 'งอชาง' },
  { code: 'aeu', nameEn: 'Akeu', nameTh: 'อาเคอะ' },
  { code: 'ahk-akha', nameEn: 'Akha', nameTh: 'อาข่า' },
  { code: 'ahk-akha-thailand', nameEn: 'Akha Thailand', nameTh: 'อาข่า ประเทศไทย' },
  { code: 'bfg', nameEn: 'Kayan', nameTh: 'กะยัน' },
  {
    code: 'blk-karen-pa-o-moulmein',
    nameEn: "Karen Pa'o Moulmein",
    nameTh: 'กะเหรี่ยงปะโอ เมาะลำเลิง',
  },
  { code: 'blk-karen-pa-o-southern', nameEn: "Karen Pa'o Southern", nameTh: 'กะเหรี่ยงปะโอ ใต้' },
  { code: 'blr-blang-shan', nameEn: 'Blang-Shan', nameTh: 'บลางชาน' },
  { code: 'blr-yi-pula-in-mengzi', nameEn: 'Yi Pula in Mengzi', nameTh: 'ยี ปูลา เม่งจื๊อ' },
  { code: 'blr-yi-pula-in-yuanyang', nameEn: 'Yi Pula in Yuanyang', nameTh: 'ยี ปูลา หยวนหยาง' },
  { code: 'blt', nameEn: 'Tai Black', nameTh: 'ไทดำ' },
  { code: 'bru', nameEn: 'Bru Eastern Tri', nameTh: 'บรู ตะวันออก ตรี' },
  { code: 'brv', nameEn: 'Bru Western Dong Luang', nameTh: 'บรูตะวันตก ดงหลวง' },
  { code: 'bwe', nameEn: 'Karen Bwe', nameTh: 'กะเหรี่ยงบะเว' },
  { code: 'bzi', nameEn: 'Bisu', nameTh: 'บีซู' },
  { code: 'cbn', nameEn: 'Nyah Kur', nameTh: 'ญัฮกุร' },
  { code: 'cdo', nameEn: 'Foochow Colloquial Chinese', nameTh: 'จีนฟูฉาว' },
  { code: 'cja', nameEn: 'Cham Cambodia', nameTh: 'ชาม กัมพูชา' },
  { code: 'cmn-chinese-huang-yuan', nameEn: 'Chinese Huang Yuan', nameTh: 'จีนหวงเยวียน' },
  {
    code: 'cmn-chinese-hubei-chongyanghua',
    nameEn: 'Chinese Hubei Chongyanghua',
    nameTh: 'จีนฮูเป่ย ฉงหยางหัว',
  },
  { code: 'cmn-chinese-lu-gu', nameEn: 'Chinese Lu Gu', nameTh: 'จีนหลู่กู่' },
  { code: 'cmn-chinese-ning-du', nameEn: 'Chinese Ning Du', nameTh: 'จีนหนิงตู๋' },
  { code: 'ctg', nameEn: 'Bangla Chittagonian', nameTh: 'บังกลา ชิตตาโกเนียน' },
  { code: 'dty', nameEn: 'Doteli', nameTh: 'โดเตลี' },
  { code: 'emn', nameEn: 'Eman', nameTh: 'เอมาน' },
  { code: 'gaa', nameEn: 'Ga', nameTh: 'กา' },
  { code: 'ghl', nameEn: 'Ghulam', nameTh: 'กลัม' },
  { code: 'haj', nameEn: 'Hajong', nameTh: 'ฮาจอง' },
  { code: 'hal', nameEn: 'Halbi', nameTh: 'ฮาลบี' },
  { code: 'hif-fiji-hindi', nameEn: 'Fiji Hindi', nameTh: 'ฮินดี ฟิจิ' },
  { code: 'hlt', nameEn: 'Nga La', nameTh: 'งะลา' },
  { code: 'hmn-hmong-daw', nameEn: 'Hmong Daw', nameTh: 'ม้งขาว' },
  { code: 'hmn-hmong-njua', nameEn: 'Hmong Njua', nameTh: 'ม้งเขียว' },
  { code: 'hmr', nameEn: 'Hmar', nameTh: 'หมาร์' },
  { code: 'hnj-hmong-lu', nameEn: 'Hmong Lu', nameTh: 'ม้งลื้อ' },
  { code: 'hnj-hmong-qho', nameEn: 'Hmong Qho', nameTh: 'ม้งโค' },
  { code: 'hnn', nameEn: 'Hanunoo', nameTh: 'ฮานูโน' },
  { code: 'hok', nameEn: 'Hokan', nameTh: 'โฮกัน' },
  { code: 'ilo', nameEn: 'Ilocano', nameTh: 'อีโลกาโน' },
  { code: 'iso', nameEn: 'Isoko', nameTh: 'อิโซโก' },
  { code: 'jpn-japanese', nameEn: 'Japanese', nameTh: 'ญี่ปุ่น' },
  { code: 'jpn-okianwan', nameEn: 'Okinawan Japanese', nameTh: 'ญี่ปุ่น โอกินาวา' },
  { code: 'kbd', nameEn: 'Kabardian', nameTh: 'คาบาร์เดียน' },
  { code: 'khb-buguo', nameEn: 'Buguo', nameTh: 'บูกูโอ' },
  { code: 'khb-lu', nameEn: 'Lu', nameTh: 'ลู' },
  { code: 'khb-thai-lu', nameEn: 'Thai Lu', nameTh: 'ไทลื้อ' },
  { code: 'khm', nameEn: 'Khmer', nameTh: 'เขมร' },
  { code: 'kjg', nameEn: 'Khmu', nameTh: 'ขมุ' },
  { code: 'kkh', nameEn: 'Khun', nameTh: 'ขุน' },
  { code: 'kmn', nameEn: 'Kumaoni', nameTh: 'กุมาอุนี' },
  { code: 'kmu', nameEn: 'Kanite', nameTh: 'คานิเต' },
  { code: 'kns', nameEn: 'Kensiu', nameTh: 'เค็นซิว' },
  { code: 'kok', nameEn: 'Konkani', nameTh: 'กอนกานี' },
  { code: 'kpw', nameEn: 'Kobon', nameTh: 'โคบอน' },
  { code: 'kte', nameEn: 'Nubian', nameTh: 'นูเบียน' },
  { code: 'kum', nameEn: 'Kumyk', nameTh: 'คูมิค' },
  { code: 'kvb', nameEn: 'Kubu', nameTh: 'กูบู' },
  { code: 'lao', nameEn: 'Lao', nameTh: 'ลาว' },
  { code: 'lik', nameEn: 'Lika', nameTh: 'ลิกา' },
  { code: 'lis-lisu', nameEn: 'Lisu', nameTh: 'ลีซู' },
  { code: 'lis-lisu-northern', nameEn: 'Lisu Northern', nameTh: 'ลีซู เหนือ' },
  { code: 'lmn', nameEn: 'Lambadi', nameTh: 'ลัมบาดี' },
  { code: 'lnd', nameEn: 'Lundayeh', nameTh: 'ลุนดาเยห์' },
  { code: 'lus-mizo', nameEn: 'Mizo', nameTh: 'มิโซ' },
  { code: 'lus-lushai', nameEn: 'Lushai', nameTh: 'ลูไช' },
  { code: 'mfa', nameEn: 'Malay Pattani', nameTh: 'มลายู ปัตตานี' },
  { code: 'mhr', nameEn: 'Mari Eastern', nameTh: 'มารี ตะวันออก' },
  { code: 'mkh-kuy', nameEn: 'Kuy', nameTh: 'กูย' },
  { code: 'mkh-suai', nameEn: 'Suai', nameTh: 'ส่วย' },
  { code: 'mnw', nameEn: 'Mon', nameTh: 'มอญ' },
  { code: 'mni', nameEn: 'Manipuri', nameTh: 'มณีปุรี' },
  { code: 'mrw', nameEn: 'Maranao', nameTh: 'มาราเนา' },
  { code: 'mya', nameEn: 'Burmese', nameTh: 'พม่า' },
  { code: 'myq', nameEn: 'Forest Maninka', nameTh: 'โฟเรสต์ มานิงกา' },
  { code: 'nod', nameEn: 'Thai Northern', nameTh: 'ไทยเหนือ-กำเมือง' },
  { code: 'npi-nepali', nameEn: 'Nepali', nameTh: 'เนปาล' },
  { code: 'npi-nepali-bhutan', nameEn: 'Nepali Bhutan', nameTh: 'เนปาล ภูฏาน' },
  { code: 'npi-nepali-kathmandu', nameEn: 'Nepali Kathmandu', nameTh: 'เนปาล กาฐมาณฑุ' },
  { code: 'nyw', nameEn: 'Nyaw', nameTh: 'ญ้อ' },
  { code: 'pce', nameEn: 'Deang Hongfenglong', nameTh: 'เดียง ฮองแฟงกลอง' },
  { code: 'pht-phu-thai', nameEn: 'Phu Thai', nameTh: 'ภูไท' },
  { code: 'pht-phu-thai-na-kae', nameEn: 'Phu Thai Na Kae', nameTh: 'ภูไท นาแก' },
  { code: 'pht-phu-thai-renu', nameEn: 'Phu Thai Renu', nameTh: 'ภูไท เรณู' },
  { code: 'prt-phai-central', nameEn: 'Phai Central', nameTh: 'ไปรกลาง' },
  { code: 'prt-phai-southern', nameEn: 'Phai Southern', nameTh: 'ไปรใต้' },
  { code: 'prt-tin-eastern', nameEn: 'Tin Eastern', nameTh: 'ลัวะ ตะวันออก' },
  { code: 'pwo', nameEn: 'Karen Pwo Western', nameTh: 'กะเหรี่ยงโป ตะวันตก' },
  { code: 'pww', nameEn: 'Karen Pwo Hod', nameTh: 'กะเหรี่ยงโป ฮอด' },
  { code: 'ryn', nameEn: 'Okinawan', nameTh: 'โอกินา' },
  { code: 'shn', nameEn: 'Shan', nameTh: 'ไทใหญ่' },
  { code: 'sia', nameEn: 'Akkadian', nameTh: 'อัคคาเดียน' },
  { code: 'sis', nameEn: 'Siuslaw', nameTh: 'ซูสลอว์' },
  { code: 'skj', nameEn: 'Seke', nameTh: 'เซเก' },
  { code: 'skr', nameEn: 'Saraiki', nameTh: 'ศรากี' },
  { code: 'sle', nameEn: 'Sholaga', nameTh: 'โชลากา' },
  { code: 'smj', nameEn: 'Lule Sami', nameTh: 'ลูเล ซามิ' },
  { code: 'smn', nameEn: 'Inari Sami', nameTh: 'อินารี ซามิ' },
  { code: 'sms', nameEn: 'Skolt Sami', nameTh: 'สคอลต์ ซามิ' },
  { code: 'sou', nameEn: 'Thai Southern', nameTh: 'ไทยใต้' },
  { code: 'tam', nameEn: 'Tamil', nameTh: 'ทมิฬ' },
  { code: 'tdd', nameEn: 'Tai Ya', nameTh: 'ไทหย่า' },
  { code: 'tha', nameEn: 'Thai Central', nameTh: 'ไทยกลาง' },
  { code: 'thm', nameEn: 'So Thavung', nameTh: 'โซ่ทะวืง' },
  { code: 'tts', nameEn: 'Thai Northeastern', nameTh: 'ไทยอีสาน' },
  { code: 'urd', nameEn: 'Urdu', nameTh: 'อูรดู' },
  { code: 'urk', nameEn: 'Urak Lawoi', nameTh: 'อูรักลาโวจ' },
  { code: 'vie-vietnamese', nameEn: 'Vietnamese', nameTh: 'เวียดนาม' },
  { code: 'vie-vietnamese-south', nameEn: 'Vietnamese South', nameTh: 'เวียดนามใต้' },
  { code: 'yno', nameEn: 'Yong', nameTh: 'ยอง' },
  { code: 'yoy', nameEn: 'Yoy', nameTh: 'โย้ย' },
  { code: 'yue', nameEn: 'Cantonese', nameTh: 'จีนกวางตุ้ง' },
  { code: 'zsm', nameEn: 'Malay Standard', nameTh: 'มลายูกลาง' },
] as const;

export const LANGUAGE_MAP: Record<LanguageCode, LanguageMeta> = LANGUAGES.reduce((acc, l) => {
  acc[l.code.toLowerCase()] = l;
  return acc;
}, {} as Record<LanguageCode, LanguageMeta>);
