// src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./styles.css";

// This hook is generated by vite-plugin-pwa
import { useRegisterSW } from "virtual:pwa-register/react";

function Root() {
  // Register the service worker and wire in the two supported callbacks
  useRegisterSW({
    immediate: true,
    onNeedRefresh() {
      // App/UpdateToast will listen for this via your own state if needed
      // (no-op here to satisfy types and ensure registration happens)
    },
    onOfflineReady() {
      // likewise a no-op here; SW gets registered
    },
    // If you want a registration callback, the correct one is:
    // onRegisteredSW(swUrl, r) {
    //   console.log('SW registered:', swUrl, r);
    // },
    // onRegisterError(error) {
    //   console.error('SW registration error', error);
    // },
  });

  return <App />;
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <Root />
  </React.StrictMode>
);
